version: '3'
services:
  db:
    image: postgres
    hostname: db
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: yekta
      POSTGRES_DB: test
  core:
    image: core
    hostname: core
    container_name: core
    restart: always
    ports:
      - 8080:80
    volumes:
      - ../configs/core.toml:/etc/config.toml
    links:
      - db
