[app]
listen = ":80"

[forwarder]
channel_size = 100
workers = 50
url = "forwarder:1234"

[database]
connection_string = "user=yekta password=secret host=db port=5432 dbname=test sslmode=disable"
dialect = "postgres"

[log]
level = "debug"
